namespace: "netapp"
name: "storagegrid"
version: "20.11.0"
readme: README.md
authors:
    - "NetApp Ansible Team <ng-ansibleteam@netapp.com>"
description: "NetApp StorageGRID Collection"
license: "GPL-2.0-or-later"
tags:
    - "storage"
homepage: https://netapp.io/configuration-management-and-automation/
