namespace: "netapp"
name: "storagegrid"
version: "21.17.0"
readme: README.md
authors:
    - "NetApp Ansible Team <ng-ansibleteam@netapp.com>"
description: "NetApp StorageGRID Collection"
license_file: COPYING
repository: https://github.com/ansible-collections/netapp.storagegrid
homepage: https://netapp.io/configuration-management-and-automation/
tags:
    - storage
    - netapp
    - storagegrid
